[build]
  publish = ".output/public"
  command = "npm install && npm run generate"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NETLIFY_NEXT_RUNTIME = "nodejs20.x"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect API calls to functions
[[redirects]]
  from = "/api/quiz/generate"
  to = "/.netlify/functions/quiz-generate"
  status = 200

[[redirects]]
  from = "/api/summary/generate"
  to = "/.netlify/functions/summary-generate"
  status = 200