[build]
  publish = "dist"
  command = "cd netlify/functions && npm install && npm run build && cd ../.. && npm run generate"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NITRO_PRESET = "netlify"
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect API calls to functions
[[redirects]]
  from = "/api/quiz/generate"
  to = "/.netlify/functions/quiz-generate"
  status = 200

[[redirects]]
  from = "/api/summary/generate"
  to = "/.netlify/functions/summary-generate"
  status = 200
