[build]
  publish = "."
  command = "echo 'Manual deployment - no build needed'"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NITRO_PRESET = "netlify"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

# Redirect API calls to functions
[[redirects]]
  from = "/api/quiz/generate"
  to = "/.netlify/functions/quiz-generate"
  status = 200

[[redirects]]
  from = "/api/summary/generate"
  to = "/.netlify/functions/summary-generate"
  status = 200
