[build]
  publish = "."
  command = "echo 'Manual deployment - no build needed'"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NITRO_PRESET = "netlify"

# Redirect API calls to functions
[[redirects]]
  from = "/api/quiz/generate"
  to = "/.netlify/functions/quiz-generate"
  status = 200

[[redirects]]
  from = "/api/summary/generate"
  to = "/.netlify/functions/summary-generate"
  status = 200
